//
// Autogenerated by Thrift Compiler (0.8.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;
var ttypes = module.exports = {};
var Dog = module.exports.Dog = function(args) {
  this.name = null;
  this.age = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    }
    if (args.age !== undefined) {
      this.age = args.age;
    }
  }
};
Dog.prototype = {};
Dog.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I16) {
        this.age = input.readI16();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Dog.prototype.write = function(output) {
  output.writeStructBegin('Dog');
  if (this.name) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.age) {
    output.writeFieldBegin('age', Thrift.Type.I16, 2);
    output.writeI16(this.age);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var User = module.exports.User = function(args) {
  this.uid = null;
  this.uname = null;
  this.usex = null;
  this.uage = null;
  this.dogs = null;
  if (args) {
    if (args.uid !== undefined) {
      this.uid = args.uid;
    }
    if (args.uname !== undefined) {
      this.uname = args.uname;
    }
    if (args.usex !== undefined) {
      this.usex = args.usex;
    }
    if (args.uage !== undefined) {
      this.uage = args.uage;
    }
    if (args.dogs !== undefined) {
      this.dogs = args.dogs;
    }
  }
};
User.prototype = {};
User.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.uid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.uname = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BOOL) {
        this.usex = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I16) {
        this.uage = input.readI16();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.dogs = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new ttypes.Dog();
          elem6.read(input);
          this.dogs.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

User.prototype.write = function(output) {
  output.writeStructBegin('User');
  if (this.uid) {
    output.writeFieldBegin('uid', Thrift.Type.STRING, 1);
    output.writeString(this.uid);
    output.writeFieldEnd();
  }
  if (this.uname) {
    output.writeFieldBegin('uname', Thrift.Type.STRING, 2);
    output.writeString(this.uname);
    output.writeFieldEnd();
  }
  if (this.usex) {
    output.writeFieldBegin('usex', Thrift.Type.BOOL, 3);
    output.writeBool(this.usex);
    output.writeFieldEnd();
  }
  if (this.uage) {
    output.writeFieldBegin('uage', Thrift.Type.I16, 4);
    output.writeI16(this.uage);
    output.writeFieldEnd();
  }
  if (this.dogs) {
    output.writeFieldBegin('dogs', Thrift.Type.LIST, 5);
    output.writeListBegin(Thrift.Type.STRUCT, this.dogs.length);
    for (var iter7 in this.dogs)
    {
      if (this.dogs.hasOwnProperty(iter7))
      {
        iter7 = this.dogs[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

